#!/usr/bin/env python3
"""Generate font.inc by extracting glyphs from the stock Victor 9000 font.

Source: V9K_NORMAL_FONT.bin - a Sirius/Victor ".CHR" character-set file:
  - 0x80-byte text/metadata header ("...NORMAL ... Sirius Systems 82/07/17...")
  - glyph data starts at offset 0x80, indexed by raw character code,
    32 bytes (16 little-endian words) per glyph.
  - bit N of each word = column N (low bit = leftmost), matching the Victor
    character generator's low->high = left->right scan order.
  - a fixed bit at row 14 / col 15 is present in every glyph; it is Victor
    cell metadata and is copied through verbatim.

We emit the same ASCII-indexed layout the RAM-test ROM expects: glyph index =
ASCII - 0x20, covering 0x20..0x5F (64 glyphs), 16 words each.

The activity spinner reuses the '^' (0x5E) glyph slot as its vertical-bar
frame (see SPIN_FRAMES in ram_test.asm). The stock '^' is a real caret, so we
substitute the stock '|' glyph (code 0x7C) into that slot to keep the spinner
showing a vertical bar.
"""

SRC = "V9K_NORMAL_FONT.bin"
DATA_OFS = 0x80        # glyph data start in the .CHR file
GLYPH_BYTES = 32       # 16 words per glyph
FIRST = 0x20
LAST = 0x5F

# ROM glyph-slot -> stock-font source code overrides (see module docstring).
SLOT_SRC = {0x5E: 0x7C}   # '^' spinner slot drawn from the stock '|' glyph


def glyph_words(data, code):
    off = DATA_OFS + code * GLYPH_BYTES
    return [data[off + r * 2] | (data[off + r * 2 + 1] << 8) for r in range(16)]


def main():
    data = open(SRC, "rb").read()
    n = LAST - FIRST + 1
    out = []
    out.append("; font.inc - ASCII-indexed font for the Victor 9000 RAM test ROM")
    out.append("; GENERATED by extractfont.py from %s - do not edit by hand." % SRC)
    out.append("; Glyph index = ASCII - 0x20 (covers 0x20..0x5F). 16 words/glyph.")
    out.append("FONT_FIRST_ASCII equ 0%02Xh" % FIRST)
    out.append("FONT_LAST_ASCII  equ 0%02Xh" % LAST)
    out.append("FONT_GLYPHS equ %d" % n)
    out.append("font_data:")
    for code in range(FIRST, LAST + 1):
        src = SLOT_SRC.get(code, code)
        words = glyph_words(data, src)
        ch = chr(code) if code != FIRST else "space"
        note = "" if src == code else "  (stock 0x%02X %r)" % (src, chr(src))
        out.append("  ; 0x%02X '%s'%s" % (code, ch, note))
        for w in words:
            out.append("    dw 0%04Xh" % w)
    open("font.inc", "w").write("\n".join(out) + "\n")
    print("wrote font.inc:", n, "glyphs from", SRC)


if __name__ == "__main__":
    main()
